version: '3.9'
services:
  app:
    container_name: react-app
    build: .
    volumes:
      - ./:/react-app
      - node_modules:/react-app/node_modules
    ports:
      - "3080:3000"
    networks:
      - react
    command: "npm start"
networks:
  react:
volumes:
  node_modules:
    driver: local
